apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: your-dockerhub-username/notification-service:latest
          ports:
            - containerPort: 3006
          env:
            - name: MONGO_URI
              value: "mongodb://admin:password@mongo:27017/food-delivery?authSource=admin"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 3006
      targetPort: 3006
  type: ClusterIP
